# Generated by Django 2.2.5 on 2020-09-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleInfo',
        ),
    ]
