# Generated by Django 2.2.5 on 2020-09-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_delete_peopleinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, 'SEX'), (1, 'MAN'), (2, 'WOMEN')], default=0, verbose_name='性别')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo', verbose_name='图书编号')),
            ],
            options={
                'verbose_name': '人物信息',
                'db_table': 'peopleinfo',
            },
        ),
    ]
